In [1]:
def matumn(a,b):
    import numpy as np
    umn = []
    for i in range(len(a[0])):
        stroka = []
        for k in range(len(b[0])):
            el = 0
            for j in range(len(b)):
                el += a[i][j]*b[j][k]
            stroka.append(el)
        umn.append(stroka)
    return np.array(umn)    

In [2]:
import numpy as np
np.set_printoptions(precision = 3, suppress = True)
A = np.array( [[5,-1,2],
               [1,4,-1],
               [1,1,1]] )
b = np.array( [8, -4, 4] ).reshape((3,1))
x0 = np.array(  [0,0,0] ).reshape((3,1))

In [3]:
lamda_max = max(np.linalg.eig(A)[0])
lamda_min = min(np.linalg.eig(A)[0])
q = (lamda_max-lamda_min)/(lamda_max+lamda_min)

In [4]:
print('СКОРОСТЬ СХОЖДЕНИЯ =', '%1.3f' % q)

СКОРОСТЬ СХОЖДЕНИЯ = 0.654


In [5]:
U = np.zeros((3,3))
L = np.zeros((3,3))
D = np.zeros((3,3))
mass = range(3)

In [6]:
for i in mass:
    D[i][i] = A[i][i]
print(D)    

[[ 5.  0.  0.]
 [ 0.  4.  0.]
 [ 0.  0.  1.]]


In [7]:
for i in mass:
    for j in range(i,3):
        U[i][j] = A[i][j]
U -= D
print(U)

[[ 0. -1.  2.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]


In [8]:
for i in mass:
    for j in range(i):
        L[i][j] = A[i][j]
print(L)
i = j = None

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  1.  0.]]


In [9]:
R = (-1)*np.array(matumn(np.linalg.inv(L + D), U)).reshape((3,3))
F = np.array(matumn(np.linalg.inv(L + D), b)).reshape((3,1))
print(F)
print(R)

[[ 1.6]
 [-1.4]
 [ 3.8]]
[[-0.    0.2  -0.4 ]
 [-0.   -0.05  0.35]
 [-0.   -0.15  0.05]]


In [10]:
x = F
print('ШАГ №'+str(1)+'\n\n', x,'\n')
for i in range(5):
    x = matumn(R,x) + F
    x = x.reshape((3,1))
    print('ШАГ №'+str(i+2)+'\n\n', x,'\n')

ШАГ №1

 [[ 1.6]
 [-1.4]
 [ 3.8]] 

ШАГ №2

 [[-0.2]
 [ 0. ]
 [ 4.2]] 

ШАГ №3

 [[-0.08]
 [ 0.07]
 [ 4.01]] 

ШАГ №4

 [[ 0.01]
 [-0.  ]
 [ 3.99]] 

ШАГ №5

 [[ 0.004]
 [-0.003]
 [ 3.999]] 

ШАГ №6

 [[-0.]
 [ 0.]
 [ 4.]] 



In [11]:
print('ИСТИННОЕ РЕШЕНИЕ\n\n')
print(np.linalg.solve(A,b))

ИСТИННОЕ РЕШЕНИЕ


[[ 0.]
 [ 0.]
 [ 4.]]


In [12]:
G = matumn(A.transpose(),A)
for i in np.linalg.eig(A)[0]:
    if i < 0:
        pol_op = False
    else:
        pol_op = True
if pol_op:
    print('СХОДИТСЯ')
else:
    print('НЕ СХОДИТСЯ')

СХОДИТСЯ
